### ISSUE TITLE
Add identifiers for CMAs

### ISSUE THREAD

**Issue by paezha** [soukhova/TTS2016R#1]
At the moment the tables lack a dictionary to other areas of interest, such as the CMAs in the region. Adding such ids would help to extract traffic analysis zones for regions of interest. In particular TTS does not seem to code the traffic analysis zones to the geography of CMAs which are important for planning purposes.

**Comment by soukhova** [comment]
The TAZ boundary now have a CMA ID and Planning Boundary ID associated, see here: https://soukhova.github.io/TTS2016R/reference/ggh_taz.html

Let me know if you had something else in mind.
