### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by paezha** [soukhova/TTS2016R#3]
Update the documentation to give an brief but informative description of the tables. At the moment the description is simply a repeat of the name of the object.

![image](https://user-images.githubusercontent.com/30074724/197186921-c517ebfb-819d-4fa5-b47c-8d2bcb22cfb1.png)

Update the documentation to clarify that "jobs" is the number of people with full time jobs that work in the TAZ.

![image](https://user-images.githubusercontent.com/30074724/197187284-d5d696f5-175c-4e15-9c3f-d3d8f54d8d08.png)

The table od_ft_tt uses "trips" but in the documentation it says "persons". I suggest keeping it as "persons" and clarify in the documentation that this table is a cross-tabulation of people by place of residence and place of employment. It is not actually trips, but a proxy for trips.

![image](https://user-images.githubusercontent.com/30074724/197187536-295f918a-3bb7-490d-a776-3f2840a5b83c.png)

**Comment by soukhova** [comment]
Updated these three points in the newest version of the package. Let me know if this is what you had in mind.
